In [9]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

import tensorflow as tf


In [10]:
# 1. PREPARAR DATOS (Tensors)
# unsqueeze(1) convierte una lista plana [1,2,3] en una matriz columna [[1],[2],[3]]
X = torch.tensor([[1.0], [2.0], [3.0], [4.0], [5.0]]) 
y = torch.tensor([[2.0], [4.0], [6.0], [8.0], [10.0]]) # La regla es y = 2x

# 2. DEFINIR EL MODELO (La Arquitectura)
# Una red simple: 1 entrada -> 1 salida (Regresión Lineal)
model = nn.Linear(in_features=1, out_features=1)

# 3. CONFIGURAR EL ENTRENADOR
# Loss (Criterio): MSE (Error Cuadrático Medio) -> Igual que en las casas
criterion = nn.MSELoss() 
# Optimizer: SGD (Descenso de Gradiente Estocástico). lr=0.01 es la velocidad de aprendizaje
optimizer = optim.SGD(model.parameters(), lr=0.01)

# 4. EL BUCLE DE ENTRENAMIENTO (Training Loop)
print("Entrenando la red neuronal...")
epochs = 100 # Número de veces que verá los datos

for epoch in range(epochs):
    # A) Forward pass: Predecir
    y_pred = model(X)
    
    # B) Calcular pérdida: ¿Qué tan mal lo hicimos?
    loss = criterion(y_pred, y)
    
    # C) Backward pass: La magia del Deep Learning
    optimizer.zero_grad() # Limpiar basura anterior
    loss.backward()       # Calcular cómo corregir el error (Gradientes)
    optimizer.step()      # Actualizar los pesos (Aprender)
    
    if (epoch+1) % 10 == 0:
        print(f'Época {epoch+1}: Error = {loss.item():.4f}')

# 5. PROBAR (INFERENCIA)
nuevo_dato = torch.tensor([[10.0]]) # Queremos saber cuánto es 2 * 10
prediccion = model(nuevo_dato)
print(f"\nSi la entrada es 10, la IA predice: {prediccion.item():.2f}")

Entrenando la red neuronal...
Época 10: Error = 0.9376
Época 20: Error = 0.3347
Época 30: Error = 0.3103
Época 40: Error = 0.2900
Época 50: Error = 0.2710
Época 60: Error = 0.2532
Época 70: Error = 0.2366
Época 80: Error = 0.2211
Época 90: Error = 0.2067
Época 100: Error = 0.1931

Si la entrada es 10, la IA predice: 18.18


In [11]:
import torch
import numpy as np
# 1. Creación de un tensor desde una lista
x_pt = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

# 2. Propiedades básicas
print(f"Forma (Shape): {x_pt.shape}")
print(f"Tipo de dato: {x_pt.dtype}")

# 3. Operación matemática y GPU
# Verificamos si hay GPU disponible, si no, usamos CPU
device = "cuda" if torch.cuda.is_available() else "cpu"
x_pt = x_pt.to(device) # Movemos el tensor explícitamente

# Multiplicación matricial: Y = X * X
y_pt = torch.matmul(x_pt, x_pt)
print(f"Resultado PyTorch:\n{y_pt}")

Forma (Shape): torch.Size([2, 2])
Tipo de dato: torch.float32
Resultado PyTorch:
tensor([[ 7., 10.],
        [15., 22.]])


In [13]:
# 1. Creación de un tensor constante
x_tf = tf.constant([[1.0, 2.0], [3.0, 4.0]])

# 2. Propiedades básicas
print(f"Forma (Shape): {x_tf.shape}")
print(f"Tipo de dato: {x_tf.dtype}")

# 3. Operación matemática y GPU
# TensorFlow maneja los dispositivos automáticamente,
# pero podemos forzarlo con un contexto.
# Nota: matmul en TF espera que los tipos coincidan exactamente.
y_tf = tf.matmul(x_tf, x_tf)

print(f"Resultado TensorFlow:\n{y_tf}")

Forma (Shape): (2, 2)
Tipo de dato: <dtype: 'float32'>
Resultado TensorFlow:
[[ 7. 10.]
 [15. 22.]]


Para asegurar que tienes el entorno listo y entiendes la manipulación básica, resuelve lo siguiente:

* Genera un tensor de números aleatorios con distribución normal (Gaussiana) de tamaño $(5, 3)$ tanto en PyTorch como en TensorFlow.

* Multiplica todos los elementos de ambos tensores por el escalar $10$.

* Calcula la media (mean) de todos los valores del tensor resultante.

* Imprime el resultado final de la media para cada librería.

Nota: Busca en la documentación o infiere cómo se generan aleatorios (randn o random.normal) y cómo calcular la media (mean o reduce_mean).

In [14]:
azar_torch=torch.normal(mean=3,std=2.5,size=(5,3))
torch_tensor=torch.tensor(azar_torch)
torch_x_10=10*torch_tensor
print(torch_x_10)

media=torch_x_10.mean()
print(media)

azar_tf=tf.random.normal(shape=(5,3),mean=3,stddev=2.5)
tensor_x_10=10*azar_tf
print(tensor_x_10)

mediatf=tf.reduce_mean(tensor_x_10)
print(mediatf)


tensor([[47.3774, 32.0470, 58.8057],
        [39.2042, 48.7437, 16.1945],
        [20.7752, 74.6154, 20.0425],
        [24.3388,  8.8040, 65.1490],
        [82.0555, 24.9321, 27.3277]])
tensor(39.3608)
tf.Tensor(
[[44.31282  26.20413  34.083576]
 [73.42786  49.97375  41.18473 ]
 [45.326202 45.82271  32.730904]
 [79.35278  72.07625  42.52083 ]
 [55.33909  22.968906 31.99442 ]], shape=(5, 3), dtype=float32)
tf.Tensor(46.48793, shape=(), dtype=float32)


C:\Users\Dark7 120gb\AppData\Local\Temp\ipykernel_11696\2100390491.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch_tensor=torch.tensor(azar_torch)
